name: "Test"
on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --rm hello-world && iptables --version && sudo modprobe --remove --remove-holders ip_tables
