name: "Test"
on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: >
          sudo update-alternatives --set iptables /usr/sbin/iptables-legacy &&
          sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy &&
          sudo systemctl restart docker &&
          docker run hello-world &&
          docker network create foo &&
          iptables --version &&
          sudo iptables-legacy -F && sudo iptables-legacy -X && sudo iptables-legacy -t nat -F && sudo iptables-legacy -t nat -X && sudo ip6tables-legacy -F && sudo ip6tables-legacy -X && sudo ip6tables-legacy -t nat -F && sudo ip6tables-legacy -t nat -X && 
          sudo iptables-legacy -L &&
          sudo ip6tables-legacy -L &&
          sudo modprobe --remove --remove-holders ip_tables
